import type { NextPage } from "next";
import Head from "next/head";
import { useRecoilState, useRecoilValue } from "recoil";
import { countState, powerCountState } from "../components/atom";
import NavBar from "../components/navbar";
import Heading from "../components/heading";
import Input from "../components/changecount";
const Home: NextPage = () => {
  const [count, setCount] = useRecoilState(countState);
  const powerCount = useRecoilValue(powerCountState);
  return (
    <div data-theme="light">
      <Head>
        <title>Daisy UI and RecoilApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-[90vh] p-6 flex flex-col">
        <NavBar title={"Counter"} />
        <Heading>Recoil & Daisy ui Template ✔️</Heading>
        <h1 className=" text-center font-mono text-6xl">{count}</h1>
        <h4 className=" text-center font-serif text-md">Power: {powerCount}</h4>
        <div className="flex-row self-center justify-center items-center menu p-3 shadow bg-base-200 rounded-box w-1/3">
          <button
            className="btn btn-primary m-4 w-24"
            onClick={(_) => setCount(count + 1)}
          >
            Increase
          </button>
          <button
            className="btn btn-success w-24 m-4"
            onClick={(_) => setCount(count - 1)}
          >
            Decrease
          </button>
        </div>
        <h3 className="text-2xl">Change Input</h3>
        <Input />
      </main>
      {/* Learn to write Footers */}
      <footer className="footer footer-center h-[10vh] p-0 bg-primary text-primary-content border-t-2 border-secondary">
        <p className="font-bold text-5xl">Footer💩</p>
      </footer>
    </div>
  );
};

export default Home;
